DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON (
  id BIGINT generated by default as identity PRIMARY KEY NOT NULL,
  name VARCHAR(50),
  last_name VARCHAR(150),
  address VARCHAR(250),
  phone_number VARCHAR(20)
);

CREATE TABLE BOOK (
    id BIGINT generated by default as identity PRIMARY KEY NOT NULL,
    personID BIGINT,
    tittle VARCHAR(100),
    author VARCHAR(150),
    available BOOLEAN NOT NULL,
    borrowing_date TIMESTAMP,
    FOREIGN KEY (personID) REFERENCES PERSON(id)
);

INSERT INTO PERSON
VALUES(1, 'Jan', 'Kolewicz', 'Moskwa, Malinowa 12', '232 332 334');
INSERT INTO PERSON
VALUES(2, 'John', 'Cena', 'Berlin, Achtung 33', '132 732 334');

INSERT INTO BOOK
VALUES(4, null, 'Zielony', 'Ellon Mask', false, CURRENT_TIMESTAMP);
INSERT INTO BOOK
VALUES(1, 1, 'Czerwony Kapturek', 'Adam Mickiewicz', false, CURRENT_TIMESTAMP);
INSERT INTO BOOK
VALUES(2, 2, 'Kapturek', 'Mickiewicz', false, CURRENT_TIMESTAMP);
INSERT INTO BOOK
VALUES(3, null, 'Czerwony8', 'A2am', true, null);
INSERT INTO BOOK
VALUES(5, null, 'Czerwony7', 'A3m', true, null);
INSERT INTO BOOK
VALUES(6, null, 'Czerwony6', 'Ad1m', true, null);
INSERT INTO BOOK
VALUES(7, null, 'Czerwony5', 'A1m', true, null);
INSERT INTO BOOK
VALUES(8, null, 'Czerwony4', 'A33', true, null);
INSERT INTO BOOK
VALUES(9, null, 'Czerwony3', 'A31', true, null);
INSERT INTO BOOK
VALUES(10, null, 'Czerwony2', 'A6am', true, null);
INSERT INTO BOOK
VALUES(11, null, 'Czerwony1', 'A67m', true, null);
INSERT INTO BOOK
VALUES(12, null, 'Zielonkawy', 'Jo7n', true, null);