DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE ADDRESS (
    id bigint generated by default as identity PRIMARY KEY NOT NULL,
    zip_code VARCHAR(10),
    city VARCHAR(100),
    street VARCHAR(100),
    apartment_number VARCHAR(20)
);

CREATE TABLE PERSON (
  id BIGINT generated by default as identity PRIMARY KEY NOT NULL,
  address_id BIGINT NOT NULL,
  name VARCHAR(50),
  last_name VARCHAR(150),
  phone_number VARCHAR(20),
  email VARCHAR(50),
  FOREIGN KEY (address_id) REFERENCES ADDRESS(id)
);

CREATE TABLE BOOK (
    id BIGINT generated by default as identity PRIMARY KEY NOT NULL,
    person_id BIGINT,
    tittle VARCHAR(100),
    author VARCHAR(150),
    available BOOLEAN NOT NULL,
    borrowing_date TIMESTAMP,
    FOREIGN KEY (person_id) REFERENCES PERSON(id)
);

CREATE TABLE USER_BOOKSTORE (
    id bigint generated by default as identity PRIMARY KEY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    active BOOLEAN NOT NULL,
    roles VARCHAR(255),
    person_id bigint NOT NULL,
    FOREIGN KEY (person_id) REFERENCES PERSON(id)
);